import{t,localized,LANGS}from'./i18n.js';import{PROFILES,getProfile,defaultProfile}from'./profiles.js';import{TOPICS,datasetFor,topicById,EXPLANATIONS}from'./lessonData.js';import{ProgressManager}from'./progressStore.js';import{esc,progressBar,visual,explanationSheet,pct}from'./uiComponents.js';
const app=document.getElementById('app'),sheet=document.getElementById('sheet-root');let audio=null,s={screen:'profile',profile:null,language:'en',mode:'kids',topicId:null,index:0,selected:[],answered:false,progress:null,practiced:{},step:'learn',recall:null};const icons={alphabet:'ABC',root_words:'-lik',meaning_builder:'🧩',whose_builder:'★',plural_builder:'🦆',accusative_builder:'🎒',dative_builder:'➡️',combo_builder:'🧱',greetings:'👋',colors:'🎨',family:'👨‍👩‍👧‍👦',deconstruct:'🔍'};const tones={alphabet:'blue',root_words:'green',meaning_builder:'purple',whose_builder:'sky',plural_builder:'amber',accusative_builder:'aqua',dative_builder:'rose',combo_builder:'indigo',greetings:'mint',colors:'sun',family:'lilac',deconstruct:'teal'};
const data=()=>datasetFor(s.topicId),item=()=>data()[s.index],name=()=>s.profile?.name||(s.language==='id'?'Ayza':'Bella'),key=()=>item()?s.topicId+'::'+item().id:'',done=()=>item()&&s.progress.isComplete(s.topicId,item().id),canNext=()=>{const tp=topicById(s.topicId)?.type;return tp==='builder'?(s.answered||done()):(done()||!!s.practiced[key()]);};
function profile(id){const p=getProfile(id)||defaultProfile();s={...s,screen:'home',profile:p,language:p.language,mode:p.mode,topicId:null,index:0,selected:[],answered:false,practiced:{}};s.progress=new ProgressManager({profileId:p.id,language:p.language,mode:p.mode});document.documentElement.lang=p.language;render()}
function open(id,i=0){Object.assign(s,{screen:'lesson',topicId:id,index:i,selected:[],answered:false,step:'learn',recall:null});render()}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rootOptions(x){const others=shuffle(data().filter(w=>w.id!==x.id).map(w=>w.word)).slice(0,2);return shuffle([x.word,...others])}
function cueVisual(x){if(x.swatch)return`<div class="visual swatch" style="background:${esc(x.swatch)}"></div>`;if(x.emoji)return`<div class="visual emoji-cue"><span>${esc(x.emoji)}</span></div>`;if(x.image)return visual(x);return`<div class="visual fallback"><span>${esc(x.fallback||x.word||'?')}</span></div>`}
function deconOptions(x){const others=shuffle(data().filter(w=>w.id!==x.id).map(w=>w.id)).slice(0,2);return shuffle([x.id,...others])}
function butterflies(){return`<div class="butterfly-burst" aria-hidden="true"><span>🦋</span><span>🦋</span><span>🦋</span><span>🦋</span><span>🦋</span></div>`}
function home(){Object.assign(s,{screen:'home',topicId:null,selected:[],answered:false});render()}
function render(){if(!s.profile||s.screen==='profile')return profiles();if(s.screen==='home')return dashboard();lesson()}
function profiles(){const l=s.language||'en',cards=PROFILES.map(p=>`<button class="profile-card" data-a="profile" data-id="${esc(p.id)}"><span>${esc(p.icon)}</span><div><strong>${esc(t(p.language,'profile'+p.id[0].toUpperCase()+p.id.slice(1))||p.name)}</strong><p>${esc(t(p.language,p.descriptionKey))}</p></div></button>`).join('');app.innerHTML=`<main class="center-shell"><section class="hero-card"><div class="brand-mark big">TR</div><h1>${esc(t(l,'appTitle'))}</h1><p>${esc(t(l,'version'))}</p></section><section class="card"><h2>${esc(t(l,'selectProfile'))}</h2><p>${esc(t(l,'selectProfileSub'))}</p><div class="profile-grid">${cards}</div></section></main>`}
function dashboard(){const l=s.language,n=name(),st=s.progress.streakCount(),all=TOPICS.flatMap(q=>datasetFor(q.id).map(x=>({q:q.id,id:x.id}))),total=all.length||1,finished=all.filter(x=>s.progress.isComplete(x.q,x.id)).length,overall=pct(finished,total),cards=TOPICS.map(q=>{const d=datasetFor(q.id),p=pct(s.progress.completedCount(q.id,d.map(x=>x.id)),d.length);return`<button class="module-card ${tones[q.id]||'blue'}" data-a="topic" data-id="${q.id}"><span class="module-art">${icons[q.id]||'★'}</span><span class="module-copy"><strong>${esc(localized(q.title,l))}</strong><em>${esc(localized(q.sub,l))}</em></span><span class="module-arrow">→</span><i style="--p:${p}%"></i></button>`}).join('');app.innerHTML=`<main class="home-page"><section class="home-header"><div class="avatar">${esc(n[0])}</div><div><h1>${esc(n)}</h1><p><span>⭐ ${st}</span> ${esc(t(l,'dayStreak'))}</p></div><button class="lang-pill" data-a="settings">🌐 ${l.toUpperCase()}</button></section><section class="laya-hero"><div class="laya-mascot">🐬</div><div class="hero-text"><h2>Merhaba, ${esc(n)}! 👋</h2><p>${l==='id'?'Ayo susun makna dalam bahasa Turki hari ini!':'Let’s build meanings in Turkish today!'}</p><button class="btn primary" data-a="topic" data-id="meaning_builder">▶ ${esc(t(l,'continue'))}</button></div></section><section class="progress-card"><div class="progress-ring" style="--p:${overall}"><strong>${overall}%</strong><span>${esc(t(l,'complete'))}</span></div><div class="progress-copy"><h3>${esc(t(l,'greetingPraise'))} <span>${esc(t(l,'greetingProgress'))}</span></h3>${progressBar(overall)}<div class="stats"><b>📘 ${total}<small>${esc(t(l,'lessons'))}</small></b><b>🏆 ${finished}<small>${esc(t(l,'done'))}</small></b><b>🔥 ${st}<small>${esc(t(l,'dayStreak'))}</small></b></div></div></section><section class="module-grid">${cards}</section><nav class="bottom-nav"><button class="active" data-a="home">🏠 ${esc(t(l,'dashboard'))}</button><button data-a="settings">☺ ${esc(t(l,'profile'))}</button></nav></main>`}
function head(title,p,total){return`<header class="lesson-head"><button class="close-x" data-a="home" aria-label="${esc(t(s.language,'dashboard'))}">×</button><h1>${esc(title)}</h1><span class="streak-pill">🔥 ${s.progress.streakCount()}</span><div class="lesson-progress"><span style="width:${p}%"></span></div><b>${s.index+1} / ${total}</b></header>`}
function guide(text){return`<section class="laya-guide"><div class="mini-laya">🐬</div><div><strong>${esc(t(s.language,'layaGuide'))}</strong><p>${esc(text)}</p></div></section>`}
function teach(x){const l=s.language,ex=EXPLANATIONS[x.explanationKey]||{},lead=s.answered?t(l,'builtMeaning'):(localized(ex.main,l)||t(l,'buildPrompt')),k=x.explanationKey?` data-a="explain" data-key="${esc(x.explanationKey)}" role="button" tabindex="0"`:'';return`<section class="laya-guide tappable"${k}><div class="mini-laya">🐬</div><div><strong>${esc(t(l,'layaGuide'))}</strong><p>${esc(lead)}</p>${x.explanationKey?`<span class="link-btn">${esc(t(l,'learnWhy'))} →</span>`:''}</div></section>`}
function acts(){const l=s.language;return`<div class="learning-actions"><button class="learn-action primary" data-a="practice"><span class="ico">✓</span><span class="lbl">${esc(t(l,'practiceDone'))}</span></button><button class="learn-action" data-a="known"><span class="ico">☆</span><span class="lbl">${esc(t(l,'alreadyKnow'))}</span></button><button class="learn-action" data-a="more"><span class="ico">↻</span><span class="lbl">${esc(t(l,'needsMorePractice'))}</span></button></div><p class="status">${esc(t(l,'practiceRule'))}</p>`}
function lesson(){const l=s.language,q=topicById(s.topicId),d=data(),x=item(),p=pct(s.progress.completedCount(s.topicId,d.map(v=>v.id)),d.length),last=s.index===d.length-1,body=q.type==='alphabet'?alphabet(x,p,q,d.length):(q.type==='root'||q.type==='vocab')?root(x,p,q,d.length):q.type==='deconstruct'?deconstruct(x,p,q,d.length):builder(x,p,q,d.length),end=last?`<button class="btn success" data-a="finish">${esc(t(l,'finishTopic'))}</button>`:`<button class="btn primary" data-a="next">${esc(t(l,'next'))}</button>`;app.innerHTML=`<main class="lesson-page">${body}<nav class="lesson-nav"><button class="btn secondary" data-a="prev" ${s.index===0?'disabled':''}>${esc(t(l,'previous'))}</button><button class="btn secondary" data-a="home">${esc(t(l,'dashboard'))}</button>${end}</nav></main>`}
function alphabet(x,p,q,n){const l=s.language,b=[];if(x.mainAudio)b.push(`<button class="sound-card" data-a="play" data-path="${x.mainAudio}">🔊 ${esc(t(l,'mainSound'))}</button>`);if(x.exampleAudio)b.push(`<button class="sound-card" data-a="play" data-path="${x.exampleAudio}">📖 ${esc(t(l,'exampleWord'))}</button>`);if(x.contrastAudio)b.push(`<button class="sound-card" data-a="play" data-path="${x.contrastAudio}">〽 ${esc(t(l,'contrastSound'))}</button>`);return`${head(localized(q.title,l),p,n)}<section class="lesson-card">${guide(localized(x.target,l))}<div class="letter-stage"><div class="letter">${esc(x.letter)}</div><div class="sound-grid">${b.join('')}</div></div><section class="example-card"><div class="example-icon">🎁</div><div><div class="word-large">${esc(x.exampleWord||'')}</div><p>${esc(localized(x.target,l))}</p></div><button class="round-sound" data-a="play" data-path="${x.exampleAudio||x.mainAudio||''}">🔊</button></section><button class="link-btn" data-a="explain" data-key="${x.explanationKey}">${esc(t(l,'learnWhy'))}</button><p id="audio-status" class="status"></p>${acts()}</section>`}
function root(x,p,q,n){const l=s.language;
  if(s.step!=='quiz'){
    return`${head(localized(q.title,l),p,n)}<section class="lesson-card">${guide(l==='id'?'Dengarkan, lihat, lalu mulai latihan.':'Listen, look, then start practice.')}<div class="prompt-card">${cueVisual(x)}<div><h2>${esc(x.word)}</h2><p>${esc(localized(x.meaning,l))}</p></div>${x.audio?`<button class="round-sound" data-a="play" data-path="${x.audio}">🔊</button>`:''}</div>${x.audio?'<p id="audio-status" class="status"></p>':''}<button class="btn primary full" data-a="root-practice">${esc(t(l,'startPractice'))}</button></section>`;
  }
  const solved=!!(s.recall&&s.recall.correct);
  const opts=(s.recall&&s.recall.opts)||rootOptions(x),wide=opts.some(w=>w.length>7);
  const grid=opts.map(w=>{const cls=s.recall&&s.recall.picked===w?(w===x.word?'right':'wrong'):(solved&&w===x.word?'right':'');return`<button class="recall-option ${cls}" data-a="root-pick" data-word="${esc(w)}" ${solved?'disabled':''}>${esc(w)}</button>`}).join('');
  const fb=solved?`<section class="success-panel"><div class="success-check">✓</div><div><h2>${esc(t(l,'successTitle'))} 🎉</h2><p><strong>${esc(x.word)}</strong> = ${esc(localized(x.meaning,l))}</p></div>${x.audio?`<button class="btn secondary" data-a="play" data-path="${x.audio}">${esc(t(l,'listen'))}</button>`:''}</section>`:(s.recall&&s.recall.picked?`<div class="feedback bad">${esc(t(l,'tryAgain'))}</div>`:'');
  return`${head(localized(q.title,l),p,n)}<section class="lesson-card">${guide(l==='id'?'Cocokkan petunjuk dengan kata Turki yang benar.':'Match the clue with the correct Turkish word.')}<div class="recall-cue">${cueVisual(x)}<p>${esc(l==='id'?'Ketuk kata Turki untuk: ':'Tap the Turkish word for: ')}<strong>${esc(localized(x.meaning,l))}</strong></p></div><div class="recall-grid${wide?' stack':''} celebration-anchor">${grid}${solved?butterflies():''}</div><div id="feedback-slot">${fb}</div>${x.audio?'<p id="audio-status" class="status"></p>':''}${solved?acts():''}</section>`}
function deconstruct(x,p,q,n){const l=s.language;
  const solved=!!(s.recall&&s.recall.correct);
  const ids=(s.recall&&s.recall.opts)||deconOptions(x);
  const grid=ids.map(id=>{const it=data().find(w=>w.id===id);const cls=s.recall&&s.recall.picked===id?(id===x.id?'right':'wrong'):(solved&&id===x.id?'right':'');return`<button class="recall-option ${cls}" data-a="decon-pick" data-id="${esc(id)}" ${solved?'disabled':''}>${esc(localized(it.meaning,l))}</button>`}).join('');
  const wide=ids.some(id=>localized(data().find(w=>w.id===id).meaning,l).length>10);
  const fb=solved?`<section class="success-panel"><div class="success-check">✓</div><div><h2>${esc(t(l,'successTitle'))} 🎉</h2><p><strong>${esc(x.word)}</strong> = ${esc(localized(x.meaning,l))}</p></div>${x.audio?`<button class="btn secondary" data-a="play" data-path="${x.audio}">${esc(t(l,'listen'))}</button>`:''}</section>`:(s.recall&&s.recall.picked?`<div class="feedback bad">${esc(t(l,'tryAgain'))}</div>`:'');
  return`${head(localized(q.title,l),p,n)}<section class="lesson-card">${guide(l==='id'?'Baca atau dengarkan, lalu pilih artinya.':'Read or listen, then choose the meaning.')}<div class="recall-cue"><div class="word-stage"><h2>${esc(x.word)}</h2>${x.audio?`<button class="round-sound" data-a="play" data-path="${x.audio}">🔊</button>`:''}</div><p>${esc(l==='id'?'Apa artinya?':'What does it mean?')}</p></div><div class="recall-grid${wide?' stack':''} celebration-anchor">${grid}${solved?butterflies():''}</div><div id="feedback-slot">${fb}</div>${x.audio?'<p id="audio-status" class="status"></p>':''}${solved?acts():''}</section>`}
function builder(x,p,q,n){const l=s.language,chosen=s.selected.length?s.selected.map((v,i)=>`<button class="chip selected" data-a="remove" data-i="${i}">${esc(v)}</button>`).join(''):`<span>${esc(t(l,'answerHere'))}</span>`,opts=x.options.map(v=>`<button class="chip" data-a="pick" data-part="${esc(v)}">${esc(v)}</button>`).join(''),ok=s.answered?`<section class="success-panel"><div class="success-check">✓</div><div><h2>${esc(t(l,'successTitle'))} 🎉</h2><p>${esc(t(l,'correct'))}</p><strong>${esc(x.finalWord)}</strong></div>${x.audio?`<button class="btn secondary" data-a="play" data-path="${x.audio}">${esc(t(l,'listen'))}</button>`:''}</section>`:'';return`${head(localized(q.title,l),p,n)}<section class="builder-screen"><section class="meaning-prompt-card">${x.image?visual({image:x.image,fallback:''}):'<div class="visual"><span>📘</span></div>'}<div><h2>${esc(localized(x.prompt,l))}</h2><p>${esc(t(l,'noFinalAnswer'))}</p></div></section>${teach(x)}<div class="answer-zone">${chosen}</div><div class="chip-grid">${opts}</div><div class="button-row celebration-anchor"><button class="btn secondary" data-a="clear">↻ ${esc(t(l,'clear'))}</button><button class="btn primary" data-a="check">✓ ${esc(t(l,'check'))}</button>${s.answered?butterflies():''}</div><div id="feedback-slot">${ok}</div><p id="audio-status" class="status">${(!s.answered&&x.audio)?esc(t(l,'audioLocked')):''}</p></section>`}
function settings(){const l=s.language,m=['kids','family','adult'].map(x=>`<button class="seg ${s.mode===x?'active':''}" data-a="mode" data-mode="${x}">${esc(t(l,x))}</button>`).join('');sheet.innerHTML=`<div class="sheet-backdrop" data-a="close"><div class="sheet"><h2>${esc(t(l,'settings'))}</h2><div class="settings-line"><span>${esc(t(l,'profile'))}</span><strong>${esc(name())}</strong></div><div class="settings-line"><span>${esc(t(l,'learningPath'))}</span><strong>${esc(LANGS[l].native)}</strong></div><label>${esc(t(l,'learnerMode'))}</label><div class="seg-row">${m}</div><button class="btn secondary full" data-a="profiles">${esc(t(l,'changeProfile'))}</button><button class="btn danger full" data-a="reset">${esc(t(l,'resetProgress'))}</button><button class="btn primary full" data-a="close">${esc(t(l,'close'))}</button></div></div>`}
function play(path){const st=document.getElementById('audio-status'),l=s.language;s.practiced[key()]=true;if(audio)audio.pause();audio=new Audio(path);if(st)st.textContent=t(l,'audioLoading');audio.onended=()=>{if(st)st.textContent=t(l,'audioReady')};audio.onerror=()=>{if(st)st.textContent=t(l,'audioError')};audio.play()}
function go(d){if(d>0&&!canNext())return alert(t(s.language,'practiceBeforeNext'));if(d>0&&!done()&&s.practiced[key()])s.progress.markComplete(s.topicId,item().id);open(s.topicId,Math.max(0,Math.min(data().length-1,s.index+d)))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='profile')return profile(b.dataset.id);if(a==='topic')return open(b.dataset.id);if(a==='home')return home();if(a==='settings')return settings();if(a==='close'){if(b.classList.contains('sheet-backdrop')&&e.target!==b)return;sheet.innerHTML='';return}if(a==='profiles'){sheet.innerHTML='';s.screen='profile';return render()}if(a==='mode'){s.mode=b.dataset.mode;s.progress=new ProgressManager({profileId:s.profile.id,language:s.language,mode:s.mode});sheet.innerHTML='';return render()}if(a==='prev')return go(-1);if(a==='next')return go(1);if(a==='finish'){if(!canNext())return alert(t(s.language,'practiceBeforeNext'));if(!done()&&s.practiced[key()])s.progress.markComplete(s.topicId,item().id);return home()}if(a==='play')return play(b.dataset.path);if(a==='root-practice'){s.step='quiz';s.recall={opts:rootOptions(item()),picked:null,correct:false};return lesson()}if(a==='root-pick'){if(s.recall&&s.recall.correct)return;const x=item(),w=b.dataset.word,ok=w===x.word;s.progress.recordAttempt(s.topicId,x.id,ok,w);s.recall={opts:(s.recall&&s.recall.opts)||rootOptions(x),picked:w,correct:ok};if(ok)s.practiced[key()]=true;return lesson()}if(a==='decon-pick'){if(s.recall&&s.recall.correct)return;const x=item(),id=b.dataset.id,ok=id===x.id;s.progress.recordAttempt(s.topicId,x.id,ok,id);s.recall={opts:(s.recall&&s.recall.opts)||deconOptions(x),picked:id,correct:ok};if(ok)s.practiced[key()]=true;return lesson()}if(a==='practice'||a==='known'){if(!s.practiced[key()])return alert(t(s.language,'practiceFirstWarning'));s.progress.markComplete(s.topicId,item().id);return lesson()}if(a==='more'){if(!s.practiced[key()])return alert(t(s.language,'practiceFirstWarning'));s.progress.recordAttempt(s.topicId,item().id,false,'more');return alert(t(s.language,'needsMoreSaved'))}if(a==='pick'){if(!s.answered){s.selected.push(b.dataset.part);lesson()}return}if(a==='remove'){s.selected.splice(+b.dataset.i,1);return lesson()}if(a==='clear'){s.selected=[];s.answered=false;return lesson()}if(a==='check'){const x=item(),ok=JSON.stringify(s.selected)===JSON.stringify(x.answerParts);s.progress.recordAttempt(s.topicId,x.id,ok,s.selected);if(ok){s.answered=true;s.progress.markComplete(s.topicId,x.id);return lesson()}document.getElementById('feedback-slot').innerHTML=`<div class="feedback bad">${esc(t(s.language,'wrong'))}</div>`;return}if(a==='reset'){s.progress.clear();sheet.innerHTML='';return render()}if(a==='explain')sheet.innerHTML=explanationSheet(s.language,b.dataset.key,item())});render();